apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: tenant
spec:
  namespaceOptions:
    quota: 5
    forbiddenAnnotations:
      deniedRegex: .*
    forbiddenLabels:
      deniedRegex: .*
