apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default
spec:
  subject:
    namespaces:
      matchExpressions:
        - key: tenant.example.com/name
          operator: Exists

  # note: openshift-ingress may not necessarily be denied if the router pod is on the same node as the destination pod
  #       this is because the router uses the host network, which cannot be selected by network policies
  ingress:
    - name: default-deny
      action: Allow
      from:
        - namespaces:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: Exists
