crds:
  install: false

manager:
  hostUsers: false
  options:
    # setup users
    administrators:
      - kind: User
        name: admin
    users:
      - kind: Group
        name: system:authenticated:oauth

    # other config
    forceTenantPrefix: true
    allowServiceAccountPromotion: true
    protectedNamespaceRegex: "(kube-.*|openshift-.*)"

# get tls working
tls:
  enableController: true
certManager:
  additionalSANS:
    - capsule-webhook-service
    - capsule-webhook-service.capsule-system
