crds:
  install: false

manager:
  hostUsers: false
  options:
    # setup users
    administrators:
      - kind: User
        name: admin
#      - kind: ServiceAccount
#        name: system:serviceaccount:openshift-kube-controller-manager:kube-controller-manager-sa
#      - kind: ServiceAccount
#        name: system:serviceaccount:openshift-kube-controller-manager:default
    users:
      - kind: Group
        name: system:authenticated:oauth

    # other config
    forceTenantPrefix: true
    allowServiceAccountPromotion: true
    protectedNamespaceRegex: "(kube-.*|openshift-.*)"

# get tls working
tls:
  enableController: true
certManager:
  additionalSANS:
    - capsule-webhook-service
    - capsule-webhook-service.capsule-system
