podSecurityContext:
  enabled: true
securityContext:
  enabled: true
jobs:
  podSecurityContext:
    enabled: false
  securityContext:
    enabled: false
  image:
    pullPolicy: Always
manager:
  image:
    pullPolicy: Always
