# these would probably be better off as just values put in by the helm chart, or
# using the namespace config operator or similar
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: allow-from-same-tenant
spec:
  resyncPeriod: 60s
  pruningOnDelete: true
  tenantSelector:
    matchLabels:
      netpol.tenant.example.com/allow-from-same-tenant: "true"
  resources:
    - rawItems:
        - apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-same-tenant
          spec:
            podSelector: {}
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        tenant.example.com/name: "{{ tenant.name }}"
            policyTypes:
              - Ingress
