apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: tenant-b
spec:
  # testing tenant namespace creation without prefix
  forceTenantPrefix: false
  owners:
  - kind: User
    name: developer
