apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  name: default
spec:
  enableTLSReconciler: true
  forceTenantPrefix: true
  overrides:
    TLSSecretName: capsule-tls
    mutatingWebhookConfigurationName: capsule-mutating-webhook-configuration
    validatingWebhookConfigurationName: capsule-validating-webhook-configuration
  protectedNamespaceRegex: "(kube-.*|openshift-.*)"
  userGroups:
    - projectcapsule.dev
    - system:authenticated:oauth