apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

  # proof of concept of allowing namespace provisioning with service accounts
  # these resources would probably go in the tenant helm chart
  - provisioner
patches:
  - path: tenant.yaml
    target:
      kind: Tenant
    options:
      allowNameChange: true
  - path: crq.yaml
    target:
      kind: ClusterResourceQuota
    options:
      allowNameChange: true
