apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - path: tenant.yaml
    target:
      kind: Tenant
    options:
      allowNameChange: true
  - path: crq.yaml
    target:
      kind: ClusterResourceQuota
    options:
      allowNameChange: true

labels:
  - pairs:
      tenant.example.com: tenant-a