apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: tenant-a
spec:
  owners:
  - kind: User
    name: developer
  namespaceOptions:
    additionalMetadata:
      labels:
        all-label: value
    additionalMetadataList:
      - labels:
          different-label: value
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: tenant-a-test
